### ISSUE TITLE
class Theme_My_Login_Walker_Nav_Menu_Edit may break menu

### ISSUE THREAD

**Issue by lampsolutions** [jfarthing84/theme-my-login#164]
If a theme or other plugin uses a custom Walker_Nav_Menu_Edit, theme-my-login will break the menu in admin backend of wordpress.

**Comment by jfarthing84** [comment]
If Theme My Login uses a custom Walker_Nav_Menu_Edit, and another plugin or theme does as well, that plugin will break the menu in the admin backend of WordPress.

Seriously, it's a collision that cannot be avoided. You can remove the walker override from one or the other, depending on which functionality is more important to you.

**Comment by lampsolutions** [comment]
If you use a third party theme or other plugins, it can be hard 
1) To evaluate what functionality you use by removing one walker filter
2) Even recognize that you have lost functionality by one walker overriding another
3) handling plugin or theme updates

Maybe showing a warning when walkers are overridden may help 
```
global $wp_filter;
    if($wp_filter["wp_edit_nav_menu_walker"])
...
```
What functionality is lost exactly if theme-my-login does not use wp_edit_nav_menu_walker filter?

**Comment by jfarthing84** [comment]
I would suggest that all plugin/theme developers use a standardized hook here, so that no matter which walker is being used, all of our code works. We are implementing the same action hook that many other plugins are: **wp_nav_menu_item_custom_fields**. I would suggest you suggest this to the other plugin in question.

That being said, removing TML's walker at this time will affect nothing as far as TML core. It will limit usage of the Restrictions extension, if one were to purchase it.
