### ISSUE TITLE
Reset password link appears to be invalid; every time

### ISSUE THREAD

**Issue by mattharrell** [jfarthing84/theme-my-login#29]
Hey Jeff, 

I've been following along quite a bit on the forums and now here in github and I'm just banging my head against the wall trying to figure out why the Lost Password link is always invalid. I can request the password rest link at http://grammarflip.com/lostpassword/ but if I click on the link I get the error, every single time. I have uninstalled and reinstalled TML and have the latest versions of everything. 

The funny thing is that it works fine on staging at http://grammarflip.staging.wpengine.com/lostpassword/ and I can't figure out what's different. 

I know you're busy Jeff and appreciate any willingness you might have to help me figure this out.

**Comment by jfarthing84** [comment]
Being that your hosted on WPEngine, I'm 99% certain that it's caching. See [this](https://wordpress.org/support/topic/password-reset-issues-3?replies=38). And if it's not that, it's probably #27.

**Comment by TacoV** [comment]
If you send the e-mail plaintext, the ampersand (&amp;) becomes an actual part of the reset url (instead of just &). This gave me problems - maybe it's your issue as well.
I'll look into a pull request to have an unescaped and an escaped version of the %reset_url% variable - this would also give the possibility of using
    <a href="%reseturl%">%reseturl%</a>
for the mail clients that don't convert the links into clickable links automatically.

(Only now I saw there is no actual code here on github ^^. Ah well, it's an easy change, if Jeff agrees he'll be able to fix it in a few minutes)

**Comment by jfarthing84** [comment]
@TacoV There is code. Switch to the 6.4 branch.
